### ISSUE TITLE
11.09. Open Tech School JS/Node/Web workshops

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#14]

**Comment by theophani** [comment]
@janl Do you know if anyone contacted the OTS people about this yet?

**Comment by janl** [comment]
pretty sure we haven’t

**Comment by rmehner** [comment]
I did, some weeks ago. @janl and @janmonschke have been in CC for that. Gonna check again once I'm back in Berlin (Thursday evening)

**Comment by rmehner** [comment]
I did, some weeks ago. Both Jans have been in CC, might have overlooked this :) At the airport right now, will check once I'm home.

**Comment by janmonschke** [comment]
Yes, OTS has been contacted and it seems that there was interest in having an event on the 12th of September. Not sure what the current state of this is. Maybe we need to ping @ligthyear again ;)

**Comment by gnunicorn** [comment]
Sorry, never got back to you about this. I was waiting for the next OTS BLN team meeting to bring it up but two were skipped and none happened since you've send me the email. I'm not personally involved in the JS group of OTS, but let me directly get you in touch with our leading coaches.

//cc @karlwestin, @sjockers, @xmartin, @gsambrotta, @autarc .

**Comment by xMartin** [comment]
Hey! Is there some background info? What about this email?

**Comment by janmonschke** [comment]
The idea is to have an OTS JS workshop during the week of JSFest.berlin. Maybe on the weekend of JSConf.eu.

**Comment by gnunicorn** [comment]
@martin, email forwarded. It's German though and I don't have the addr of karl and autarc....

**Comment by xMartin** [comment]
Ok, cool. Let's organize a JS workshop. Count me in as an organizer and I can coordinate, too.

**Comment by karlwestin** [comment]
Sure sounds like a good idea, 
Is the idea to have an event directed to beginners, or should we create a more advanced workshop? (people from the node beginners workshop asked about DB:s, testing, etc)

**Comment by finnp** [comment]
I only now saw this discussion, but I would like to do a nodeschool (discussion here: https://github.com/nodeschool/discussions/issues/439). I thought about September 10th for a date, even though that would collide with BerlinJS.

What is the state of the JS workshop?

**Comment by xMartin** [comment]
Just checked the schedule and where we would fit in the OTS JavaScript for Beginners workshop. Is there a reason nothing happens on Sunday? I'd definitely take the Sunday. The workshop we usually do is a two-day workshop but Saturday is pretty packed with stuff although of course we can always add more. We could also think about reducing the workshop to one day (Sunday only). What do you think?

**Comment by finnp** [comment]
I think Sunday would be fine, since I don't go to the JSConf.EU. If the OTS workshop is the whole Sunday, probably many people who go to JSConf can't help. But I think we would get enough coaches anyway (The OTS courses are mainly self-directed right?)

Maybe I would try to addionally organize a nodeschool on Wednesday, depending on how much help you need organizing. How much support do your have from OTS? Like a e.g. getting a venue?

**Comment by xMartin** [comment]
I was going for the weekend so participants don't have to take a day (or two) off. That of course means no conference people can coach but I don't see how that could work at all anyway. And yes, I assume we find enough coaches. I'm checking with co.up as a venue.

Let's move the detailed discussion over here: http://discourse.opentechschool.org/t/javascript-for-beginners-workshop-jsfest-berlin/875
